### ISSUE TITLE
Renderer screenshot 404 not found

### ISSUE THREAD

**Issue by annyanich** [AndreiBarsan/Yeti#1]
Hey, I was looking at your project, and I noticed the screenshot you link to in your README does not seem to be available.

https://camo.githubusercontent.com/2a4be24907ebe4698556e6273176218abf636e86/687474703a2f2f7369656765646f672e636f6d2f72656e64657265722e6a7067 gives me a 404 not found.

**Comment by AndreiBarsan** [comment]
Hi,

Thanks for pointing that out! The screenshot seems to have been lost at some point, as GitHub changed some things about how they host images.

I haven't gotten around to running this on my newer computer, but I'll keep this in mind and update the screenshots when I manage to do it!

**Comment by AndreiBarsan** [comment]
Here's another screenshot I had lying around. IMHO it's not good enough to replace the old one which is 404ing, but it should give you some idea of what the renderer does! :) 

![nessieisonpar](https://cloud.githubusercontent.com/assets/1260898/22547281/4ceeffd4-e941-11e6-9722-ec136eaf7a41.png)

**Comment by annyanich** [comment]
I forgot about this!  Thanks for giving me a look at that.  :)

**Comment by AndreiBarsan** [comment]
Added a bunch of screenshots and fixed README, so I feel I can close this now. Thanks once again for pointing this out!
